[package]
name = "echo"
version = "0.1.0"
authors = ["Matei Adriel <rafaeladriel11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.12.0", features=["allocator_api"] } # Arena allocator
rustc-hash = "1.1.0" # Fast hashmap (will remove soon)
smallvec = "1.10.0" # Vectors which start on the stack (will remove soon)
rayon = "1.7.0" # Multithreading
rand = "0.8.5" # RNG
dialoguer = "0.10.2" # Console stuff
indicatif = "0.17.2" # Console stuff
const_for = "0.1.2" # Conmpile time loops

[profile.release]
debug = true
# lto = true
